/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaInicialController;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Casa
 */
public class TelaInicial extends javax.swing.JFrame {

    private final TelaInicialController controller;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.controller = new TelaInicialController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKW = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnLimpa = new javax.swing.JButton();
        lblErro = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Potência do aparelho (em W)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tempo de uso por dia (em horas)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Ou");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tempo de uso por dia (em minutos)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Preço do kWh");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtKW.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKWActionPerformed(evt);
            }
        });
        getContentPane().add(txtKW, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 90, 40));

        txtHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHorasFocusGained(evt);
            }
        });
        txtHoras.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtHorasInputMethodTextChanged(evt);
            }
        });
        txtHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 40));
        getContentPane().add(txtCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, 40));

        btnCalcular.setBackground(new java.awt.Color(0, 102, 255));
        btnCalcular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 130, 32));

        lblResult.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 190, 40));

        lblValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblValor.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 160, 40));

        btnLimpa.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpa.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpa.setText("Limpar tela");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 130, 32));

        lblErro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblErro.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(lblErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 220, 20));

        txtMinutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMinutosFocusGained(evt);
            }
        });
        txtMinutos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMinutosInputMethodTextChanged(evt);
            }
        });
        txtMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosActionPerformed(evt);
            }
        });
        getContentPane().add(txtMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 40));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 204));
        lblTitulo.setText("Quanto gasta seu aparelho?");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblRS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRS.setText("R$");
        getContentPane().add(lblRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        lblFundo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKWActionPerformed
        //
    }//GEN-LAST:event_txtKWActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //Calcular gastos
        this.controller.calcularGastos();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        // Limpar tela
        this.controller.limparTela();
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void txtMinutosInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMinutosInputMethodTextChanged
        //
        
    }//GEN-LAST:event_txtMinutosInputMethodTextChanged

    private void txtHorasInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtHorasInputMethodTextChanged
        //
        
    }//GEN-LAST:event_txtHorasInputMethodTextChanged

    private void txtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasActionPerformed
        //
        
    }//GEN-LAST:event_txtHorasActionPerformed

    private void txtMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosActionPerformed
        //
        
    }//GEN-LAST:event_txtMinutosActionPerformed

    private void txtHorasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorasFocusGained
        //Limpa o conteúdo do txtMinutos
        this.controller.limparCampo(this.txtMinutos);
    }//GEN-LAST:event_txtHorasFocusGained

    private void txtMinutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMinutosFocusGained
        //Limpa o conteúdo do txtHoras
        this.controller.limparCampo(this.txtHoras);
    }//GEN-LAST:event_txtMinutosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    public JTextField getTxtCusto() {
        return txtCusto;
    }

    public void setTxtCusto(JTextField txtCusto) {
        this.txtCusto = txtCusto;
    }

    public JTextField getTxtHoras() {
        return txtHoras;
    }

    public void setTxtHoras(JTextField txtHoras) {
        this.txtHoras = txtHoras;
    }

    public JTextField getTxtKW() {
        return txtKW;
    }

    public void setTxtKW(JTextField txtKW) {
        this.txtKW = txtKW;
    }

    public JLabel getLblResult() {
        return lblResult;
    }

    public void setLblResult(JLabel lblResult) {
        this.lblResult = lblResult;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public JLabel getLblErro() {
        return lblErro;
    }

    public void setLblErro(JLabel lblErro) {
        this.lblErro = lblErro;
    }

    public JTextField getTxtMinutos() {
        return txtMinutos;
    }

    public void setTxtMinutos(JTextField txtMinutos) {
        this.txtMinutos = txtMinutos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblRS;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtKW;
    private javax.swing.JTextField txtMinutos;
    // End of variables declaration//GEN-END:variables
    
}
